import type { NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

const Home: NextPage = () => {
    const { data: session, status } = useSession();
    const authorized = status === "authenticated" && !!session?.user;

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
                {authorized ? (
                    <div>
                        <h1 className="text-2xl font-bold">Welcome {session?.user?.name}</h1>
                        <button onClick={() => signOut()}>Sign out</button>
                        <div className="p-5" />
                        <h1>{JSON.stringify(session, undefined, 4)}</h1>
                    </div>
                ) : (
                    <div>
                        <h1 className="text-2xl font-bold">Welcome</h1>
                        <button onClick={() => signIn()}>Sign in</button>
                    </div>
                )}
            </main>
        </>
    );
};

export default Home;
